name: Topic Proposal
description: File a proposal for a topic
title: "[Topic]: "
labels: ["proposed topic"]
assignees:
  - rustc
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to offer a topic proposal!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: rustc-module
    attributes:
      label: Which rustc topic would you like to suggest?
      description: Also tell us, which rustc module if different from topic?
      placeholder: 
      value:  
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Relevant code file URL
      description: Please provide a link to the module.
      placeholder: 
      value:  
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.rust-lang.org/policies/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

          